Parameters:
  ApplicationName:
    Description: Name of application.
    Type: String
    Default: "dirtbag"

AWSTemplateFormatVersion: 2010-09-09
Resources:
  TerraformStateBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Sub
        - ${OrgName}-terraform-state
        - {OrgName: !Ref ApplicationName}
      VersioningConfiguration:
        Status: Enabled