install:
	python3 -m venv dirtbag-venv
	. dirtbag-venv/bin/activate
	pip3 install -r requirements.txt

run:
	. dirtbag-venv/bin/activate
	python3 app/app.py

run-nohup:
	. dirtbag-venv/bin/activate
	nohup python3 app/app.py &
